# Preparation #

In [1]:
import torch
from torch.utils.data import Dataset
torch.manual_seed(0)


# Create a Simple Dataset #

In [5]:
class MyDataset(Dataset):
    def __init__(self, length=100, transform=None):
        super(MyDataset, self).__init__()
        self.length = length
        self.transform = transform
        self.x = 2 * torch.ones(length, 2)
        self.y = torch.ones(length, 1)

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample

    
    def __len__(self):
        return self.length

In [6]:
dataset = MyDataset()

In [7]:
dataset[1]

(tensor([2., 2.]), tensor([1.]))

In [8]:
len(dataset)

100

# Apply Transformations #

In [15]:
class add_mult:
    def __init__(self, addx = 1, muly = 2):
        self.addx = addx
        self.muly = muly

    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        sample = x , y
        return sample

In [16]:
mytransform = add_mult()
dataset2 = MyDataset(transform= mytransform)

In [17]:
dataset2[1]

(tensor([3., 3.]), tensor([2.]))

# Use torchvision.transforms #

In [18]:
from torchvision import transforms

# Compose Multiple Transforms #

In [29]:
data_transform = transforms.Compose([add_mult(), add_mult()])

In [33]:
Dataset3 = MyDataset(transform=data_transform)

In [34]:
Dataset3[1]

(tensor([4., 4.]), tensor([4.]))